### ISSUE TITLE
Ultrasound images containing colour are incorrectly displayed

### ISSUE THREAD

**Issue by wolberth** [horosproject/horos#118]
When watching an ultrasound image containig color doppler signals with HOROS 2.0, my images are still displayed incorrectly. Furthermore ultrasound loops containing color doppler data are also not displayed correctly.
Are there any tricks for a quick fix of the problem? I have change all presets according to previous posts on the problem. Any help is greatly appreciated. 
kind regards, Thomas
![unnamed 0001](https://cloud.githubusercontent.com/assets/8587706/16569916/baa70bea-423c-11e6-847b-f2a5e3f8bea0.jpg)

**Comment by wolberth** [comment]
... and here an example movie
[example.mp4.zip](https://github.com/horosproject/horos/files/346852/example.mp4.zip)

**Comment by fvpolpeta** [comment]
Please see:

https://github.com/horosproject/horos/issues/88

Use the configuration in the screenshots for your Horos 2.0

Best

**Comment by wolberth** [comment]
Actually, I am using exactly all the configurations from the screenshots. The only difference Is that I am using a single screen. But unfortunately the issue persists. I am using current version 2.0. Could not download the nightly build that was referred to.

**Comment by fvpolpeta** [comment]
Please, send a anonymized sample of the series.

Tks

**Comment by wolberth** [comment]
[Archiv.zip](https://github.com/horosproject/horos/files/351685/Archiv.zip)

Here are the files
Thank you very much for your help!

Kind regards,
Thomas

**Comment by wolberth** [comment]
May I ask you how my uploaded files display on your system?

kind regards, 

Thomas Wolber

**Comment by fvpolpeta** [comment]
Course, sorry for this.

The bug is confirmed and is being investigated.

All new feedback will be posted here.

Tks

**Comment by wolberth** [comment]
Any news about this bug? I have sponsored a bug fix (2 x 100 USD). Hope this will be of help.

kind regards,
Th. Wolber

**Comment by wolberth** [comment]
Hi, how are things going? I would really like to use horos, however this bug is a show-stopper for me. As I am a physician, I am not able to work on it ... so what can I do to get this fixed? Please help or advise me what I can do ...
Thank you!

**Comment by aglv** [comment]
~~Please try checking/unchecking the _Use VOI LUT if available_ in _Preferences_ > _Viewers_ (in the _Miscellaneous_ box at the bottom, left column, 7th item). Does it change anything?~~

**Comment by fvpolpeta** [comment]
Hey Aglv, that seems to be related to the downsize of the bitsample at:

DCMPix.m::
if ( [colorspace hasPrefix:@"PALETTE"]) { bitsAllocated = 8; isRGB = YES; NSLog(@"Palette depth conveted to 8 bit");}

The "Use VOI LUT..."  can be triggered in Horos because the DICOM loader is not based on Papyrus, and there are some conditional statements that avoid that.

Thus, these 16 bit usound images are being mishandled in Horos. I will be investigating how to read/load them properly. Any of your precious help is very welcome.

Regards

**Comment by wolberth** [comment]
Thanks for the hint. However, it doesn’t change anything in my case.

kind regards, 
Thomas

**Comment by aglv** [comment]
~~@wolberth Please also try disabling the _Full 32-bit OpenGL pipeline_~~

**Comment by wolberth** [comment]
This has already been disabled, problem still exists. I will try to test on different versions of OS X. Certainly doesn't work on Yosemite.

**Comment by wolberth** [comment]
HI, is there any chance this bug will be fixed? Unfortunately, still can not use HOROS for viewing Echo images with colour.

**Comment by wolberth** [comment]
By the way, checking the Use VOI LUT in Preferences does not work - checkmark disappears by itself after one second.

**Comment by cateaddis** [comment]
Any progress on this? 

I am completely unable to use Horos, which I otherwise love. I can't check the Use VOI LUT box either, and I have tried reintalling this program soooo many times. Just installed the 2.2.0 build... same problem.

**Comment by aglv** [comment]
Hey, I've inspected this a little further. ~~Horos doesn't seem to support the 16-bit PALETTE format used in your images. It cuts the pixels down to 8-bit, so every pixel is shown as two (this doesn't make sense) and only the top half of the image is spread over the display.~~

Actually 16-bit palettes were supported but there was a bug. It should be fixed now.

**Comment by wolberth** [comment]
With Horos 2.2.0, Rev. 20170725, downloaded on Oct 17 2107, I still experience the same problem with my iMac Mid 2014 running OSX Sierra 10.12.6.

Any idea how to fix this?

**Comment by aglv** [comment]
It’s fixed, but not yet included in a public release.

**Comment by Blummy** [comment]
Hi, Was this problem ever resolved as I am having this issue?

**Comment by wolberth** [comment]
I don‘t know. I made some financial contributions to the company to fix the issue, however, as a physician, I could not contribute any code. As far as I know, the issue remains unresolved until today.
